// Mocks generated by Mockito 5.4.6 from annotations
// in polired/test/services/handlers/post_command_handlers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;
import 'dart:ui' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:polired/models/events/post_event.dart' as _i9;
import 'package:polired/models/feed_context.dart' as _i10;
import 'package:polired/models/post_model.dart' as _i5;
import 'package:polired/providers/post_store_provider.dart' as _i8;
import 'package:polired/services/api_service.dart' as _i2;
import 'package:polired/services/navigation_bus.dart' as _i12;
import 'package:polired/services/post_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostService extends _i1.Mock implements _i3.PostService {
  MockPostService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<List<_i5.PostModel>>> fetchGlobalFeed({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGlobalFeed, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>.value(
              _FakeApiResult_0<List<_i5.PostModel>>(
                this,
                Invocation.method(#fetchGlobalFeed, [], {
                  #page: page,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>);

  @override
  _i4.Future<_i2.ApiResult<List<_i5.PostModel>>> fetchCommunityFeed({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommunityFeed, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>.value(
              _FakeApiResult_0<List<_i5.PostModel>>(
                this,
                Invocation.method(#fetchCommunityFeed, [], {
                  #page: page,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>);

  @override
  _i4.Future<_i2.ApiResult<List<_i5.PostModel>>> fetchArticlesFeed({
    int? page = 1,
    int? limit = 20,
    String? categoria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchArticlesFeed, [], {
              #page: page,
              #limit: limit,
              #categoria: categoria,
            }),
            returnValue: _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>.value(
              _FakeApiResult_0<List<_i5.PostModel>>(
                this,
                Invocation.method(#fetchArticlesFeed, [], {
                  #page: page,
                  #limit: limit,
                  #categoria: categoria,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>);

  @override
  _i4.Future<_i2.ApiResult<List<_i5.PostModel>>> fetchFeedByNetwork(
    String? redId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchFeedByNetwork,
              [redId],
              {#page: page, #limit: limit},
            ),
            returnValue: _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>.value(
              _FakeApiResult_0<List<_i5.PostModel>>(
                this,
                Invocation.method(
                  #fetchFeedByNetwork,
                  [redId],
                  {#page: page, #limit: limit},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> createPost({
    required String? feedContext,
    String? titulo,
    required String? contenido,
    required String? categoria,
    String? comunidadId,
    List<String>? mediaUrls,
    List<_i6.File>? imageFiles,
    double? aspectRatio = 1.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #feedContext: feedContext,
              #titulo: titulo,
              #contenido: contenido,
              #categoria: categoria,
              #comunidadId: comunidadId,
              #mediaUrls: mediaUrls,
              #imageFiles: imageFiles,
              #aspectRatio: aspectRatio,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#createPost, [], {
                  #feedContext: feedContext,
                  #titulo: titulo,
                  #contenido: contenido,
                  #categoria: categoria,
                  #comunidadId: comunidadId,
                  #mediaUrls: mediaUrls,
                  #imageFiles: imageFiles,
                  #aspectRatio: aspectRatio,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> createArticle({
    required String? feedContext,
    String? titulo,
    required String? descripcion,
    required dynamic precio,
    required String? categoria,
    String? comunidadId,
    String? tipoContenido = 'texto',
    List<String>? mediaUrls,
    List<_i6.File>? imageFiles,
    double? aspectRatio = 1.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createArticle, [], {
              #feedContext: feedContext,
              #titulo: titulo,
              #descripcion: descripcion,
              #precio: precio,
              #categoria: categoria,
              #comunidadId: comunidadId,
              #tipoContenido: tipoContenido,
              #mediaUrls: mediaUrls,
              #imageFiles: imageFiles,
              #aspectRatio: aspectRatio,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#createArticle, [], {
                  #feedContext: feedContext,
                  #titulo: titulo,
                  #descripcion: descripcion,
                  #precio: precio,
                  #categoria: categoria,
                  #comunidadId: comunidadId,
                  #tipoContenido: tipoContenido,
                  #mediaUrls: mediaUrls,
                  #imageFiles: imageFiles,
                  #aspectRatio: aspectRatio,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> createExtendedPost({
    required String? titulo,
    String? contenido,
    String? comunidadId,
    String? tipoContenido = 'texto',
    String? categoria,
    List<String>? mediaUrls,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createExtendedPost, [], {
              #titulo: titulo,
              #contenido: contenido,
              #comunidadId: comunidadId,
              #tipoContenido: tipoContenido,
              #categoria: categoria,
              #mediaUrls: mediaUrls,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#createExtendedPost, [], {
                  #titulo: titulo,
                  #contenido: contenido,
                  #comunidadId: comunidadId,
                  #tipoContenido: tipoContenido,
                  #categoria: categoria,
                  #mediaUrls: mediaUrls,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  String cleanId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cleanId, [id]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#cleanId, [id]),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> deletePost(
    String? postId, {
    required bool? isArticle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId], {#isArticle: isArticle}),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(
                  #deletePost,
                  [postId],
                  {#isArticle: isArticle},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<bool> toggleLike(String? postId, bool? isCurrentlyLiked) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [postId, isCurrentlyLiked]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> toggleSave(String? postId, bool? isCurrentlySaved) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSave, [postId, isCurrentlySaved]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> getCommentsTree(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentsTree, [postId]),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#getCommentsTree, [postId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<List<dynamic>>> getPostLikes(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostLikes, [postId]),
            returnValue: _i4.Future<_i2.ApiResult<List<dynamic>>>.value(
              _FakeApiResult_0<List<dynamic>>(
                this,
                Invocation.method(#getPostLikes, [postId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<dynamic>>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> reportarPublicacion({
    required String? publicacionId,
    required String? tipo,
    required String? descripcion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportarPublicacion, [], {
              #publicacionId: publicacionId,
              #tipo: tipo,
              #descripcion: descripcion,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#reportarPublicacion, [], {
                  #publicacionId: publicacionId,
                  #tipo: tipo,
                  #descripcion: descripcion,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> reportarArticulo({
    required String? articuloId,
    required String? tipo,
    required String? descripcion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportarArticulo, [], {
              #articuloId: articuloId,
              #tipo: tipo,
              #descripcion: descripcion,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#reportarArticulo, [], {
                  #articuloId: articuloId,
                  #tipo: tipo,
                  #descripcion: descripcion,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> createComment(
    String? postId,
    String? contenido,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [postId, contenido]),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#createComment, [postId, contenido]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> replyComment(
    String? commentId,
    String? contenido,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replyComment, [commentId, contenido]),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#replyComment, [commentId, contenido]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<List<_i5.PostModel>>> fetchSavedPosts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSavedPosts, []),
            returnValue: _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>.value(
              _FakeApiResult_0<List<_i5.PostModel>>(
                this,
                Invocation.method(#fetchSavedPosts, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>);

  @override
  _i4.Future<_i2.ApiResult<List<_i5.PostModel>>> fetchLikedPosts({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLikedPosts, [], {
              #page: page,
              #limit: limit,
            }),
            returnValue: _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>.value(
              _FakeApiResult_0<List<_i5.PostModel>>(
                this,
                Invocation.method(#fetchLikedPosts, [], {
                  #page: page,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.PostModel>>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> reportApp({
    required String? tipo,
    required String? descripcion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportApp, [], {
              #tipo: tipo,
              #descripcion: descripcion,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#reportApp, [], {
                  #tipo: tipo,
                  #descripcion: descripcion,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);
}

/// A class which mocks [PostStoreProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostStoreProvider extends _i1.Mock implements _i8.PostStoreProvider {
  MockPostStoreProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i9.UIEvent> get uiEvents =>
      (super.noSuchMethod(
            Invocation.getter(#uiEvents),
            returnValue: _i4.Stream<_i9.UIEvent>.empty(),
          )
          as _i4.Stream<_i9.UIEvent>);

  @override
  int get globalVersion =>
      (super.noSuchMethod(Invocation.getter(#globalVersion), returnValue: 0)
          as int);

  @override
  bool get isSocialStateInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isSocialStateInitialized),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, _i5.PostModel> get postsById =>
      (super.noSuchMethod(
            Invocation.getter(#postsById),
            returnValue: <String, _i5.PostModel>{},
          )
          as Map<String, _i5.PostModel>);

  @override
  Set<String> get likedPostIds =>
      (super.noSuchMethod(
            Invocation.getter(#likedPostIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> get savedPostIds =>
      (super.noSuchMethod(
            Invocation.getter(#savedPostIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  int get feedVersionHome =>
      (super.noSuchMethod(Invocation.getter(#feedVersionHome), returnValue: 0)
          as int);

  @override
  int get feedVersionGlobal =>
      (super.noSuchMethod(Invocation.getter(#feedVersionGlobal), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.PostModel? getPost(String? id) =>
      (super.noSuchMethod(Invocation.method(#getPost, [id])) as _i5.PostModel?);

  @override
  Set<String> getContextIndex(_i10.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getContextIndex, [context]),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<_i10.FeedContext> getContextsForPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getContextsForPost, [postId]),
            returnValue: <_i10.FeedContext>[],
          )
          as List<_i10.FeedContext>);

  @override
  String getFingerprint(_i10.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getFingerprint, [context]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getFingerprint, [context]),
            ),
          )
          as String);

  @override
  int nextSequenceNumber(_i10.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#nextSequenceNumber, [context]),
            returnValue: 0,
          )
          as int);

  @override
  void setSocialHydration(List<String>? likedIds, List<String>? savedIds) =>
      super.noSuchMethod(
        Invocation.method(#setSocialHydration, [likedIds, savedIds]),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostCreated(_i9.PostCreated? event) => super.noSuchMethod(
    Invocation.method(#applyPostCreated, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostDeleted(_i9.PostDeleted? event) => super.noSuchMethod(
    Invocation.method(#applyPostDeleted, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostUpdated(_i9.PostUpdated? event) => super.noSuchMethod(
    Invocation.method(#applyPostUpdated, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyStateEvent(_i9.StateEvent? event) => super.noSuchMethod(
    Invocation.method(#applyStateEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emitUIEvent(_i9.UIEvent? event) => super.noSuchMethod(
    Invocation.method(#emitUIEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void addBatchPosts(List<_i5.PostModel>? posts, {_i10.FeedContext? context}) =>
      super.noSuchMethod(
        Invocation.method(#addBatchPosts, [posts], {#context: context}),
        returnValueForMissingStub: null,
      );

  @override
  void incrementCommentsCount(String? postId) => super.noSuchMethod(
    Invocation.method(#incrementCommentsCount, [postId]),
    returnValueForMissingStub: null,
  );

  @override
  void incrementFeedVersionHome() => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionHome, []),
    returnValueForMissingStub: null,
  );

  @override
  void incrementFeedVersionGlobal() => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionGlobal, []),
    returnValueForMissingStub: null,
  );

  @override
  int getNetworkFeedVersion(String? networkId) =>
      (super.noSuchMethod(
            Invocation.method(#getNetworkFeedVersion, [networkId]),
            returnValue: 0,
          )
          as int);

  @override
  void incrementFeedVersionNetwork(String? networkId) => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionNetwork, [networkId]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.PostModel> resolvePosts(List<String>? ids, int? version) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePosts, [ids, version]),
            returnValue: <_i5.PostModel>[],
          )
          as List<_i5.PostModel>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationBus extends _i1.Mock implements _i12.NavigationBus {
  MockNavigationBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i9.NavigationEvent> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i9.NavigationEvent>.empty(),
          )
          as _i4.Stream<_i9.NavigationEvent>);

  @override
  void dispatch(_i9.NavigationEvent? event) => super.noSuchMethod(
    Invocation.method(#dispatch, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
