// Mocks generated by Mockito 5.4.6 from annotations
// in polired/test/providers/explore_networks_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:polired/models/network_story_model.dart' as _i5;
import 'package:polired/services/api_service.dart' as _i2;
import 'package:polired/services/network_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i3.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<List<dynamic>>> getRedesDelEstudiante() =>
      (super.noSuchMethod(
            Invocation.method(#getRedesDelEstudiante, []),
            returnValue: _i4.Future<_i2.ApiResult<List<dynamic>>>.value(
              _FakeApiResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRedesDelEstudiante, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<dynamic>>>);

  @override
  _i4.Future<_i2.ApiResult<List<_i5.NetworkStoryModel>>>
  getRedesEstudianteStories() =>
      (super.noSuchMethod(
            Invocation.method(#getRedesEstudianteStories, []),
            returnValue:
                _i4.Future<_i2.ApiResult<List<_i5.NetworkStoryModel>>>.value(
                  _FakeApiResult_0<List<_i5.NetworkStoryModel>>(
                    this,
                    Invocation.method(#getRedesEstudianteStories, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.NetworkStoryModel>>>);

  @override
  _i4.Future<_i2.ApiResult<List<_i5.NetworkStoryModel>>>
  getAvailableNetworksStories() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableNetworksStories, []),
            returnValue:
                _i4.Future<_i2.ApiResult<List<_i5.NetworkStoryModel>>>.value(
                  _FakeApiResult_0<List<_i5.NetworkStoryModel>>(
                    this,
                    Invocation.method(#getAvailableNetworksStories, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.NetworkStoryModel>>>);

  @override
  _i4.Future<_i2.ApiResult<List<dynamic>>> getRedes() =>
      (super.noSuchMethod(
            Invocation.method(#getRedes, []),
            returnValue: _i4.Future<_i2.ApiResult<List<dynamic>>>.value(
              _FakeApiResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRedes, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<dynamic>>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> unirseRed(String? redId) =>
      (super.noSuchMethod(
            Invocation.method(#unirseRed, [redId]),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#unirseRed, [redId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<Map<String, dynamic>>> getNetworkProfile(
    String? redId, {
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getNetworkProfile,
              [redId],
              {#page: page, #limit: limit},
            ),
            returnValue: _i4.Future<_i2.ApiResult<Map<String, dynamic>>>.value(
              _FakeApiResult_0<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #getNetworkProfile,
                  [redId],
                  {#page: page, #limit: limit},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> solicitarCreacionRed({
    required String? nombre,
    required String? descripcion,
    required String? proposito,
    String? fotoPerfil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#solicitarCreacionRed, [], {
              #nombre: nombre,
              #descripcion: descripcion,
              #proposito: proposito,
              #fotoPerfil: fotoPerfil,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#solicitarCreacionRed, [], {
                  #nombre: nombre,
                  #descripcion: descripcion,
                  #proposito: proposito,
                  #fotoPerfil: fotoPerfil,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> solicitarVerificacionRed({
    required String? redId,
    required String? nombreRed,
    required String? fechaCreacionRed,
    required int? cantidadMiembros,
    required String? correoInstitucional,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#solicitarVerificacionRed, [], {
              #redId: redId,
              #nombreRed: nombreRed,
              #fechaCreacionRed: fechaCreacionRed,
              #cantidadMiembros: cantidadMiembros,
              #correoInstitucional: correoInstitucional,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#solicitarVerificacionRed, [], {
                  #redId: redId,
                  #nombreRed: nombreRed,
                  #fechaCreacionRed: fechaCreacionRed,
                  #cantidadMiembros: cantidadMiembros,
                  #correoInstitucional: correoInstitucional,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> solicitarOficializacionRed({
    required String? redId,
    required String? nombreRed,
    required String? fechaCreacionRed,
    required int? cantidadMiembros,
    required String? dependencia,
    required String? cargo,
    required String? correoInstitucional,
    required String? justificacion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#solicitarOficializacionRed, [], {
              #redId: redId,
              #nombreRed: nombreRed,
              #fechaCreacionRed: fechaCreacionRed,
              #cantidadMiembros: cantidadMiembros,
              #dependencia: dependencia,
              #cargo: cargo,
              #correoInstitucional: correoInstitucional,
              #justificacion: justificacion,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#solicitarOficializacionRed, [], {
                  #redId: redId,
                  #nombreRed: nombreRed,
                  #fechaCreacionRed: fechaCreacionRed,
                  #cantidadMiembros: cantidadMiembros,
                  #dependencia: dependencia,
                  #cargo: cargo,
                  #correoInstitucional: correoInstitucional,
                  #justificacion: justificacion,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> reportNetwork({
    required String? redId,
    required String? tipo,
    required String? descripcion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportNetwork, [], {
              #redId: redId,
              #tipo: tipo,
              #descripcion: descripcion,
            }),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#reportNetwork, [], {
                  #redId: redId,
                  #tipo: tipo,
                  #descripcion: descripcion,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<dynamic>> salirseRed(String? redId) =>
      (super.noSuchMethod(
            Invocation.method(#salirseRed, [redId]),
            returnValue: _i4.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#salirseRed, [redId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<dynamic>>);

  @override
  _i4.Future<_i2.ApiResult<Map<String, dynamic>>> getAdminNetworkInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getAdminNetworkInfo, []),
            returnValue: _i4.Future<_i2.ApiResult<Map<String, dynamic>>>.value(
              _FakeApiResult_0<Map<String, dynamic>>(
                this,
                Invocation.method(#getAdminNetworkInfo, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<Map<String, dynamic>>>);
}
