// Mocks generated by Mockito 5.4.6 from annotations
// in polired/test/providers/messages_inbox_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/foundation.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:polired/models/conversation_model.dart' as _i7;
import 'package:polired/models/network_story_model.dart' as _i9;
import 'package:polired/repositories/conversations_repository.dart' as _i5;
import 'package:polired/services/api_service.dart' as _i2;
import 'package:polired/services/network_service.dart' as _i8;
import 'package:polired/services/socket_service.dart' as _i10;
import 'package:pusher_channels_flutter/pusher_channels_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePusherChannelsFlutter_1 extends _i1.SmartFake
    implements _i3.PusherChannelsFlutter {
  _FakePusherChannelsFlutter_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConversationsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationsRepository extends _i1.Mock
    implements _i5.ConversationsRepository {
  MockConversationsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ApiResult<List<_i7.ConversationModel>>> fetchConversations() =>
      (super.noSuchMethod(
            Invocation.method(#fetchConversations, []),
            returnValue:
                _i6.Future<_i2.ApiResult<List<_i7.ConversationModel>>>.value(
                  _FakeApiResult_0<List<_i7.ConversationModel>>(
                    this,
                    Invocation.method(#fetchConversations, []),
                  ),
                ),
          )
          as _i6.Future<_i2.ApiResult<List<_i7.ConversationModel>>>);

  @override
  _i6.Future<_i2.ApiResult<String>> getOrCreateConversation(
    String? contactId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateConversation, [contactId]),
            returnValue: _i6.Future<_i2.ApiResult<String>>.value(
              _FakeApiResult_0<String>(
                this,
                Invocation.method(#getOrCreateConversation, [contactId]),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<String>>);
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i8.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ApiResult<List<dynamic>>> getRedesDelEstudiante() =>
      (super.noSuchMethod(
            Invocation.method(#getRedesDelEstudiante, []),
            returnValue: _i6.Future<_i2.ApiResult<List<dynamic>>>.value(
              _FakeApiResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRedesDelEstudiante, []),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<List<dynamic>>>);

  @override
  _i6.Future<_i2.ApiResult<List<_i9.NetworkStoryModel>>>
  getRedesEstudianteStories() =>
      (super.noSuchMethod(
            Invocation.method(#getRedesEstudianteStories, []),
            returnValue:
                _i6.Future<_i2.ApiResult<List<_i9.NetworkStoryModel>>>.value(
                  _FakeApiResult_0<List<_i9.NetworkStoryModel>>(
                    this,
                    Invocation.method(#getRedesEstudianteStories, []),
                  ),
                ),
          )
          as _i6.Future<_i2.ApiResult<List<_i9.NetworkStoryModel>>>);

  @override
  _i6.Future<_i2.ApiResult<List<_i9.NetworkStoryModel>>>
  getAvailableNetworksStories() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableNetworksStories, []),
            returnValue:
                _i6.Future<_i2.ApiResult<List<_i9.NetworkStoryModel>>>.value(
                  _FakeApiResult_0<List<_i9.NetworkStoryModel>>(
                    this,
                    Invocation.method(#getAvailableNetworksStories, []),
                  ),
                ),
          )
          as _i6.Future<_i2.ApiResult<List<_i9.NetworkStoryModel>>>);

  @override
  _i6.Future<_i2.ApiResult<List<dynamic>>> getRedes() =>
      (super.noSuchMethod(
            Invocation.method(#getRedes, []),
            returnValue: _i6.Future<_i2.ApiResult<List<dynamic>>>.value(
              _FakeApiResult_0<List<dynamic>>(
                this,
                Invocation.method(#getRedes, []),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<List<dynamic>>>);

  @override
  _i6.Future<_i2.ApiResult<dynamic>> unirseRed(String? redId) =>
      (super.noSuchMethod(
            Invocation.method(#unirseRed, [redId]),
            returnValue: _i6.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#unirseRed, [redId]),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<dynamic>>);

  @override
  _i6.Future<_i2.ApiResult<Map<String, dynamic>>> getNetworkProfile(
    String? redId, {
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getNetworkProfile,
              [redId],
              {#page: page, #limit: limit},
            ),
            returnValue: _i6.Future<_i2.ApiResult<Map<String, dynamic>>>.value(
              _FakeApiResult_0<Map<String, dynamic>>(
                this,
                Invocation.method(
                  #getNetworkProfile,
                  [redId],
                  {#page: page, #limit: limit},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<Map<String, dynamic>>>);

  @override
  _i6.Future<_i2.ApiResult<dynamic>> solicitarCreacionRed({
    required String? nombre,
    required String? descripcion,
    required String? proposito,
    String? fotoPerfil,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#solicitarCreacionRed, [], {
              #nombre: nombre,
              #descripcion: descripcion,
              #proposito: proposito,
              #fotoPerfil: fotoPerfil,
            }),
            returnValue: _i6.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#solicitarCreacionRed, [], {
                  #nombre: nombre,
                  #descripcion: descripcion,
                  #proposito: proposito,
                  #fotoPerfil: fotoPerfil,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<dynamic>>);

  @override
  _i6.Future<_i2.ApiResult<dynamic>> solicitarVerificacionRed({
    required String? redId,
    required String? nombreRed,
    required String? fechaCreacionRed,
    required int? cantidadMiembros,
    required String? correoInstitucional,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#solicitarVerificacionRed, [], {
              #redId: redId,
              #nombreRed: nombreRed,
              #fechaCreacionRed: fechaCreacionRed,
              #cantidadMiembros: cantidadMiembros,
              #correoInstitucional: correoInstitucional,
            }),
            returnValue: _i6.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#solicitarVerificacionRed, [], {
                  #redId: redId,
                  #nombreRed: nombreRed,
                  #fechaCreacionRed: fechaCreacionRed,
                  #cantidadMiembros: cantidadMiembros,
                  #correoInstitucional: correoInstitucional,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<dynamic>>);

  @override
  _i6.Future<_i2.ApiResult<dynamic>> solicitarOficializacionRed({
    required String? redId,
    required String? nombreRed,
    required String? fechaCreacionRed,
    required int? cantidadMiembros,
    required String? dependencia,
    required String? cargo,
    required String? correoInstitucional,
    required String? justificacion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#solicitarOficializacionRed, [], {
              #redId: redId,
              #nombreRed: nombreRed,
              #fechaCreacionRed: fechaCreacionRed,
              #cantidadMiembros: cantidadMiembros,
              #dependencia: dependencia,
              #cargo: cargo,
              #correoInstitucional: correoInstitucional,
              #justificacion: justificacion,
            }),
            returnValue: _i6.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#solicitarOficializacionRed, [], {
                  #redId: redId,
                  #nombreRed: nombreRed,
                  #fechaCreacionRed: fechaCreacionRed,
                  #cantidadMiembros: cantidadMiembros,
                  #dependencia: dependencia,
                  #cargo: cargo,
                  #correoInstitucional: correoInstitucional,
                  #justificacion: justificacion,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<dynamic>>);

  @override
  _i6.Future<_i2.ApiResult<dynamic>> reportNetwork({
    required String? redId,
    required String? tipo,
    required String? descripcion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportNetwork, [], {
              #redId: redId,
              #tipo: tipo,
              #descripcion: descripcion,
            }),
            returnValue: _i6.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#reportNetwork, [], {
                  #redId: redId,
                  #tipo: tipo,
                  #descripcion: descripcion,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<dynamic>>);

  @override
  _i6.Future<_i2.ApiResult<dynamic>> salirseRed(String? redId) =>
      (super.noSuchMethod(
            Invocation.method(#salirseRed, [redId]),
            returnValue: _i6.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#salirseRed, [redId]),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<dynamic>>);

  @override
  _i6.Future<_i2.ApiResult<Map<String, dynamic>>> getAdminNetworkInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getAdminNetworkInfo, []),
            returnValue: _i6.Future<_i2.ApiResult<Map<String, dynamic>>>.value(
              _FakeApiResult_0<Map<String, dynamic>>(
                this,
                Invocation.method(#getAdminNetworkInfo, []),
              ),
            ),
          )
          as _i6.Future<_i2.ApiResult<Map<String, dynamic>>>);
}

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i10.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PusherChannelsFlutter get pusher =>
      (super.noSuchMethod(
            Invocation.getter(#pusher),
            returnValue: _FakePusherChannelsFlutter_1(
              this,
              Invocation.getter(#pusher),
            ),
          )
          as _i3.PusherChannelsFlutter);

  @override
  _i4.ValueNotifier<_i10.SocketConnectionPhase> get connectionPhase =>
      (super.noSuchMethod(
            Invocation.getter(#connectionPhase),
            returnValue: _FakeValueNotifier_2<_i10.SocketConnectionPhase>(
              this,
              Invocation.getter(#connectionPhase),
            ),
          )
          as _i4.ValueNotifier<_i10.SocketConnectionPhase>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i6.Future<void> connect(String? jwtToken, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [jwtToken, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void on(String? event, void Function(dynamic)? handler) => super.noSuchMethod(
    Invocation.method(#on, [event, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void off(String? event, [void Function(dynamic)? handler]) =>
      super.noSuchMethod(
        Invocation.method(#off, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnectInternal({required bool? clearPhase}) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectInternal, [], {
              #clearPhase: clearPhase,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearAllListeners() => super.noSuchMethod(
    Invocation.method(#clearAllListeners, []),
    returnValueForMissingStub: null,
  );
}
