// Mocks generated by Mockito 5.4.6 from annotations
// in polired/test/providers/notification_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i11;
import 'dart:ui' as _i12;

import 'package:flutter/foundation.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:polired/models/notification_model.dart' as _i8;
import 'package:polired/providers/auth_provider.dart' as _i10;
import 'package:polired/services/api_service.dart' as _i2;
import 'package:polired/services/auth_service.dart' as _i5;
import 'package:polired/services/notification_service.dart' as _i6;
import 'package:polired/services/socket_service.dart' as _i9;
import 'package:pusher_channels_flutter/pusher_channels_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePusherChannelsFlutter_1 extends _i1.SmartFake
    implements _i3.PusherChannelsFlutter {
  _FakePusherChannelsFlutter_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_3 extends _i1.SmartFake implements _i5.AuthResult {
  _FakeAuthResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i6.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.ApiResult<List<_i8.NotificationModel>>> getNotificaciones() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificaciones, []),
            returnValue:
                _i7.Future<_i2.ApiResult<List<_i8.NotificationModel>>>.value(
                  _FakeApiResult_0<List<_i8.NotificationModel>>(
                    this,
                    Invocation.method(#getNotificaciones, []),
                  ),
                ),
          )
          as _i7.Future<_i2.ApiResult<List<_i8.NotificationModel>>>);

  @override
  _i7.Future<_i2.ApiResult<dynamic>> marcarLeida(String? notifId) =>
      (super.noSuchMethod(
            Invocation.method(#marcarLeida, [notifId]),
            returnValue: _i7.Future<_i2.ApiResult<dynamic>>.value(
              _FakeApiResult_0<dynamic>(
                this,
                Invocation.method(#marcarLeida, [notifId]),
              ),
            ),
          )
          as _i7.Future<_i2.ApiResult<dynamic>>);
}

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i9.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PusherChannelsFlutter get pusher =>
      (super.noSuchMethod(
            Invocation.getter(#pusher),
            returnValue: _FakePusherChannelsFlutter_1(
              this,
              Invocation.getter(#pusher),
            ),
          )
          as _i3.PusherChannelsFlutter);

  @override
  _i4.ValueNotifier<_i9.SocketConnectionPhase> get connectionPhase =>
      (super.noSuchMethod(
            Invocation.getter(#connectionPhase),
            returnValue: _FakeValueNotifier_2<_i9.SocketConnectionPhase>(
              this,
              Invocation.getter(#connectionPhase),
            ),
          )
          as _i4.ValueNotifier<_i9.SocketConnectionPhase>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i7.Future<void> connect(String? jwtToken, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [jwtToken, userId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void on(String? event, void Function(dynamic)? handler) => super.noSuchMethod(
    Invocation.method(#on, [event, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void off(String? event, [void Function(dynamic)? handler]) =>
      super.noSuchMethod(
        Invocation.method(#off, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> disconnectInternal({required bool? clearPhase}) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectInternal, [], {
              #clearPhase: clearPhase,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void clearAllListeners() => super.noSuchMethod(
    Invocation.method(#clearAllListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i10.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.AuthStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i10.AuthStatus.loading,
          )
          as _i10.AuthStatus);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isSuspended =>
      (super.noSuchMethod(Invocation.getter(#isSuspended), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> syncProfileFromServer() =>
      (super.noSuchMethod(
            Invocation.method(#syncProfileFromServer, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i5.AuthResult> register({
    required String? nombre,
    required String? apellido,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #nombre: nombre,
              #apellido: apellido,
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i5.AuthResult>.value(
              _FakeAuthResult_3(
                this,
                Invocation.method(#register, [], {
                  #nombre: nombre,
                  #apellido: apellido,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.AuthResult>);

  @override
  _i7.Future<bool> completarPerfil(
    String? username, {
    String? fotoPerfil,
    String? biografia,
    _i11.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completarPerfil,
              [username],
              {
                #fotoPerfil: fotoPerfil,
                #biografia: biografia,
                #imageFile: imageFile,
              },
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void incrementPublicacionesCount() => super.noSuchMethod(
    Invocation.method(#incrementPublicacionesCount, []),
    returnValueForMissingStub: null,
  );

  @override
  void decrementPublicacionesCount() => super.noSuchMethod(
    Invocation.method(#decrementPublicacionesCount, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> actualizarPerfil({
    required String? nombre,
    required String? apellido,
    required String? username,
    required String? biografia,
    _i11.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarPerfil, [], {
              #nombre: nombre,
              #apellido: apellido,
              #username: username,
              #biografia: biografia,
              #imageFile: imageFile,
            }),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i5.AuthResult> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i7.Future<_i5.AuthResult>.value(
              _FakeAuthResult_3(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i7.Future<_i5.AuthResult>);

  @override
  _i7.Future<_i5.AuthResult> actualizarPassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarPassword, [
              currentPassword,
              newPassword,
            ]),
            returnValue: _i7.Future<_i5.AuthResult>.value(
              _FakeAuthResult_3(
                this,
                Invocation.method(#actualizarPassword, [
                  currentPassword,
                  newPassword,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.AuthResult>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
