// Mocks generated by Mockito 5.4.6 from annotations
// in polired/test/widgets/post_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i14;
import 'dart:ui' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:polired/models/commands/feed_command.dart' as _i2;
import 'package:polired/models/events/post_event.dart' as _i6;
import 'package:polired/models/feed_context.dart' as _i8;
import 'package:polired/models/post_model.dart' as _i7;
import 'package:polired/providers/auth_provider.dart' as _i13;
import 'package:polired/providers/post_store_provider.dart' as _i4;
import 'package:polired/services/auth_service.dart' as _i3;
import 'package:polired/services/command_bus.dart' as _i11;
import 'package:polired/services/handlers/command_handler.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommandResult_0 extends _i1.SmartFake implements _i2.CommandResult {
  _FakeCommandResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostStoreProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostStoreProvider extends _i1.Mock implements _i4.PostStoreProvider {
  MockPostStoreProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.UIEvent> get uiEvents =>
      (super.noSuchMethod(
            Invocation.getter(#uiEvents),
            returnValue: _i5.Stream<_i6.UIEvent>.empty(),
          )
          as _i5.Stream<_i6.UIEvent>);

  @override
  int get globalVersion =>
      (super.noSuchMethod(Invocation.getter(#globalVersion), returnValue: 0)
          as int);

  @override
  bool get isSocialStateInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isSocialStateInitialized),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, _i7.PostModel> get postsById =>
      (super.noSuchMethod(
            Invocation.getter(#postsById),
            returnValue: <String, _i7.PostModel>{},
          )
          as Map<String, _i7.PostModel>);

  @override
  Set<String> get likedPostIds =>
      (super.noSuchMethod(
            Invocation.getter(#likedPostIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> get savedPostIds =>
      (super.noSuchMethod(
            Invocation.getter(#savedPostIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  int get feedVersionHome =>
      (super.noSuchMethod(Invocation.getter(#feedVersionHome), returnValue: 0)
          as int);

  @override
  int get feedVersionGlobal =>
      (super.noSuchMethod(Invocation.getter(#feedVersionGlobal), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.PostModel? getPost(String? id) =>
      (super.noSuchMethod(Invocation.method(#getPost, [id])) as _i7.PostModel?);

  @override
  Set<String> getContextIndex(_i8.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getContextIndex, [context]),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<_i8.FeedContext> getContextsForPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getContextsForPost, [postId]),
            returnValue: <_i8.FeedContext>[],
          )
          as List<_i8.FeedContext>);

  @override
  String getFingerprint(_i8.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getFingerprint, [context]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getFingerprint, [context]),
            ),
          )
          as String);

  @override
  int nextSequenceNumber(_i8.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#nextSequenceNumber, [context]),
            returnValue: 0,
          )
          as int);

  @override
  void setSocialHydration(List<String>? likedIds, List<String>? savedIds) =>
      super.noSuchMethod(
        Invocation.method(#setSocialHydration, [likedIds, savedIds]),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostCreated(_i6.PostCreated? event) => super.noSuchMethod(
    Invocation.method(#applyPostCreated, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostDeleted(_i6.PostDeleted? event) => super.noSuchMethod(
    Invocation.method(#applyPostDeleted, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostUpdated(_i6.PostUpdated? event) => super.noSuchMethod(
    Invocation.method(#applyPostUpdated, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyStateEvent(_i6.StateEvent? event) => super.noSuchMethod(
    Invocation.method(#applyStateEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emitUIEvent(_i6.UIEvent? event) => super.noSuchMethod(
    Invocation.method(#emitUIEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void addBatchPosts(List<_i7.PostModel>? posts, {_i8.FeedContext? context}) =>
      super.noSuchMethod(
        Invocation.method(#addBatchPosts, [posts], {#context: context}),
        returnValueForMissingStub: null,
      );

  @override
  void incrementCommentsCount(String? postId) => super.noSuchMethod(
    Invocation.method(#incrementCommentsCount, [postId]),
    returnValueForMissingStub: null,
  );

  @override
  void incrementFeedVersionHome() => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionHome, []),
    returnValueForMissingStub: null,
  );

  @override
  void incrementFeedVersionGlobal() => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionGlobal, []),
    returnValueForMissingStub: null,
  );

  @override
  int getNetworkFeedVersion(String? networkId) =>
      (super.noSuchMethod(
            Invocation.method(#getNetworkFeedVersion, [networkId]),
            returnValue: 0,
          )
          as int);

  @override
  void incrementFeedVersionNetwork(String? networkId) => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionNetwork, [networkId]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i7.PostModel> resolvePosts(List<String>? ids, int? version) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePosts, [ids, version]),
            returnValue: <_i7.PostModel>[],
          )
          as List<_i7.PostModel>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CommandBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandBus extends _i1.Mock implements _i11.CommandBus {
  MockCommandBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void registerHandler<T extends _i2.FeedCommand>(
    _i12.CommandHandler<T>? handler,
  ) => super.noSuchMethod(
    Invocation.method(#registerHandler, [handler]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.CommandResult> dispatch<T extends _i2.FeedCommand>(
    T? command,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#dispatch, [command]),
            returnValue: _i5.Future<_i2.CommandResult>.value(
              _FakeCommandResult_0(
                this,
                Invocation.method(#dispatch, [command]),
              ),
            ),
          )
          as _i5.Future<_i2.CommandResult>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i13.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.AuthStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i13.AuthStatus.loading,
          )
          as _i13.AuthStatus);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isSuspended =>
      (super.noSuchMethod(Invocation.getter(#isSuspended), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> syncProfileFromServer() =>
      (super.noSuchMethod(
            Invocation.method(#syncProfileFromServer, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.AuthResult> register({
    required String? nombre,
    required String? apellido,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #nombre: nombre,
              #apellido: apellido,
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#register, [], {
                  #nombre: nombre,
                  #apellido: apellido,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<bool> completarPerfil(
    String? username, {
    String? fotoPerfil,
    String? biografia,
    _i14.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completarPerfil,
              [username],
              {
                #fotoPerfil: fotoPerfil,
                #biografia: biografia,
                #imageFile: imageFile,
              },
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void incrementPublicacionesCount() => super.noSuchMethod(
    Invocation.method(#incrementPublicacionesCount, []),
    returnValueForMissingStub: null,
  );

  @override
  void decrementPublicacionesCount() => super.noSuchMethod(
    Invocation.method(#decrementPublicacionesCount, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> actualizarPerfil({
    required String? nombre,
    required String? apellido,
    required String? username,
    required String? biografia,
    _i14.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarPerfil, [], {
              #nombre: nombre,
              #apellido: apellido,
              #username: username,
              #biografia: biografia,
              #imageFile: imageFile,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.AuthResult> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i5.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<_i3.AuthResult> actualizarPassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarPassword, [
              currentPassword,
              newPassword,
            ]),
            returnValue: _i5.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#actualizarPassword, [
                  currentPassword,
                  newPassword,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResult>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
