// Mocks generated by Mockito 5.4.6 from annotations
// in polired/test/screens/profile_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:polired/models/events/post_event.dart' as _i13;
import 'package:polired/models/feed_context.dart' as _i15;
import 'package:polired/models/network_story_model.dart' as _i10;
import 'package:polired/models/post_model.dart' as _i14;
import 'package:polired/providers/auth_provider.dart' as _i5;
import 'package:polired/providers/my_profile_feed_provider.dart' as _i11;
import 'package:polired/providers/network_provider.dart' as _i9;
import 'package:polired/providers/post_store_provider.dart' as _i12;
import 'package:polired/services/auth_service.dart' as _i2;
import 'package:polired/services/socket_service.dart' as _i17;
import 'package:pusher_channels_flutter/pusher_channels_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePusherChannelsFlutter_1 extends _i1.SmartFake
    implements _i3.PusherChannelsFlutter {
  _FakePusherChannelsFlutter_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i5.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AuthStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i5.AuthStatus.loading,
          )
          as _i5.AuthStatus);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isSuspended =>
      (super.noSuchMethod(Invocation.getter(#isSuspended), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> syncProfileFromServer() =>
      (super.noSuchMethod(
            Invocation.method(#syncProfileFromServer, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.AuthResult> register({
    required String? nombre,
    required String? apellido,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #nombre: nombre,
              #apellido: apellido,
              #email: email,
              #password: password,
            }),
            returnValue: _i6.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#register, [], {
                  #nombre: nombre,
                  #apellido: apellido,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResult>);

  @override
  _i6.Future<bool> completarPerfil(
    String? username, {
    String? fotoPerfil,
    String? biografia,
    _i7.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completarPerfil,
              [username],
              {
                #fotoPerfil: fotoPerfil,
                #biografia: biografia,
                #imageFile: imageFile,
              },
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void incrementPublicacionesCount() => super.noSuchMethod(
    Invocation.method(#incrementPublicacionesCount, []),
    returnValueForMissingStub: null,
  );

  @override
  void decrementPublicacionesCount() => super.noSuchMethod(
    Invocation.method(#decrementPublicacionesCount, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> actualizarPerfil({
    required String? nombre,
    required String? apellido,
    required String? username,
    required String? biografia,
    _i7.File? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarPerfil, [], {
              #nombre: nombre,
              #apellido: apellido,
              #username: username,
              #biografia: biografia,
              #imageFile: imageFile,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.AuthResult> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i6.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResult>);

  @override
  _i6.Future<_i2.AuthResult> actualizarPassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#actualizarPassword, [
              currentPassword,
              newPassword,
            ]),
            returnValue: _i6.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#actualizarPassword, [
                  currentPassword,
                  newPassword,
                ]),
              ),
            ),
          )
          as _i6.Future<_i2.AuthResult>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NetworkProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkProvider extends _i1.Mock implements _i9.NetworkProvider {
  MockNetworkProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<dynamic> get redes =>
      (super.noSuchMethod(Invocation.getter(#redes), returnValue: <dynamic>[])
          as List<dynamic>);

  @override
  bool get hasLoadedOnce =>
      (super.noSuchMethod(Invocation.getter(#hasLoadedOnce), returnValue: false)
          as bool);

  @override
  _i9.FeedStatus get feedStatus =>
      (super.noSuchMethod(
            Invocation.getter(#feedStatus),
            returnValue: _i9.FeedStatus.idle,
          )
          as _i9.FeedStatus);

  @override
  bool get loadingPosts =>
      (super.noSuchMethod(Invocation.getter(#loadingPosts), returnValue: false)
          as bool);

  @override
  bool get emptyFeed =>
      (super.noSuchMethod(Invocation.getter(#emptyFeed), returnValue: false)
          as bool);

  @override
  List<_i10.NetworkStoryModel> get networkStories =>
      (super.noSuchMethod(
            Invocation.getter(#networkStories),
            returnValue: <_i10.NetworkStoryModel>[],
          )
          as List<_i10.NetworkStoryModel>);

  @override
  List<String> get homePostIds =>
      (super.noSuchMethod(
            Invocation.getter(#homePostIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get isLoadingInitialFeed =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingInitialFeed),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoadingMoreFeed =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingMoreFeed),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasMoreFeed =>
      (super.noSuchMethod(Invocation.getter(#hasMoreFeed), returnValue: false)
          as bool);

  @override
  set pendingAutoSelectNetworkId(String? value) => super.noSuchMethod(
    Invocation.setter(#pendingAutoSelectNetworkId, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setLoadedOnce() => super.noSuchMethod(
    Invocation.method(#setLoadedOnce, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetLoadedOnce() => super.noSuchMethod(
    Invocation.method(#resetLoadedOnce, []),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadStudentNetworks() =>
      (super.noSuchMethod(
            Invocation.method(#loadStudentNetworks, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> selectNetwork(_i10.NetworkStoryModel? network) =>
      (super.noSuchMethod(
            Invocation.method(#selectNetwork, [network]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> selectNetworkById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#selectNetworkById, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadMoreForNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreForNetwork, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refreshHomeFeed() =>
      (super.noSuchMethod(
            Invocation.method(#refreshHomeFeed, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fetchRedesDelEstudiante() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRedesDelEstudiante, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fetchRedes() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRedes, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> unirseRedes(List<String>? redesIds) =>
      (super.noSuchMethod(
            Invocation.method(#unirseRedes, [redesIds]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> abandonarRed(String? redId) =>
      (super.noSuchMethod(
            Invocation.method(#abandonarRed, [redId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void prependPostId(String? id) => super.noSuchMethod(
    Invocation.method(#prependPostId, [id]),
    returnValueForMissingStub: null,
  );

  @override
  int removePostId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removePostId, [id]),
            returnValue: 0,
          )
          as int);

  @override
  void insertPostId(int? index, String? id) => super.noSuchMethod(
    Invocation.method(#insertPostId, [index, id]),
    returnValueForMissingStub: null,
  );

  @override
  void replacePostId(String? oldId, String? newId) => super.noSuchMethod(
    Invocation.method(#replacePostId, [oldId, newId]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MyProfileFeedProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyProfileFeedProvider extends _i1.Mock
    implements _i11.MyProfileFeedProvider {
  MockMyProfileFeedProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoadingFeed =>
      (super.noSuchMethod(Invocation.getter(#isLoadingFeed), returnValue: false)
          as bool);

  @override
  bool get isLoadingMoreFeed =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingMoreFeed),
            returnValue: false,
          )
          as bool);

  @override
  List<String> get postIds =>
      (super.noSuchMethod(Invocation.getter(#postIds), returnValue: <String>[])
          as List<String>);

  @override
  bool get hasMoreFeed =>
      (super.noSuchMethod(Invocation.getter(#hasMoreFeed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> fetchInitialFeed(String? myUserId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchInitialFeed, [myUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fetchMoreFeed(String? myUserId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMoreFeed, [myUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void prependPostId(String? id) => super.noSuchMethod(
    Invocation.method(#prependPostId, [id]),
    returnValueForMissingStub: null,
  );

  @override
  int removePostId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removePostId, [id]),
            returnValue: 0,
          )
          as int);

  @override
  void insertPostId(int? index, String? id) => super.noSuchMethod(
    Invocation.method(#insertPostId, [index, id]),
    returnValueForMissingStub: null,
  );

  @override
  void replacePostId(String? oldId, String? newId) => super.noSuchMethod(
    Invocation.method(#replacePostId, [oldId, newId]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PostStoreProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostStoreProvider extends _i1.Mock implements _i12.PostStoreProvider {
  MockPostStoreProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i13.UIEvent> get uiEvents =>
      (super.noSuchMethod(
            Invocation.getter(#uiEvents),
            returnValue: _i6.Stream<_i13.UIEvent>.empty(),
          )
          as _i6.Stream<_i13.UIEvent>);

  @override
  int get globalVersion =>
      (super.noSuchMethod(Invocation.getter(#globalVersion), returnValue: 0)
          as int);

  @override
  bool get isSocialStateInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isSocialStateInitialized),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, _i14.PostModel> get postsById =>
      (super.noSuchMethod(
            Invocation.getter(#postsById),
            returnValue: <String, _i14.PostModel>{},
          )
          as Map<String, _i14.PostModel>);

  @override
  Set<String> get likedPostIds =>
      (super.noSuchMethod(
            Invocation.getter(#likedPostIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> get savedPostIds =>
      (super.noSuchMethod(
            Invocation.getter(#savedPostIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  int get feedVersionHome =>
      (super.noSuchMethod(Invocation.getter(#feedVersionHome), returnValue: 0)
          as int);

  @override
  int get feedVersionGlobal =>
      (super.noSuchMethod(Invocation.getter(#feedVersionGlobal), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i14.PostModel? getPost(String? id) =>
      (super.noSuchMethod(Invocation.method(#getPost, [id]))
          as _i14.PostModel?);

  @override
  Set<String> getContextIndex(_i15.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getContextIndex, [context]),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<_i15.FeedContext> getContextsForPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getContextsForPost, [postId]),
            returnValue: <_i15.FeedContext>[],
          )
          as List<_i15.FeedContext>);

  @override
  String getFingerprint(_i15.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#getFingerprint, [context]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#getFingerprint, [context]),
            ),
          )
          as String);

  @override
  int nextSequenceNumber(_i15.FeedContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#nextSequenceNumber, [context]),
            returnValue: 0,
          )
          as int);

  @override
  void setSocialHydration(List<String>? likedIds, List<String>? savedIds) =>
      super.noSuchMethod(
        Invocation.method(#setSocialHydration, [likedIds, savedIds]),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostCreated(_i13.PostCreated? event) => super.noSuchMethod(
    Invocation.method(#applyPostCreated, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostDeleted(_i13.PostDeleted? event) => super.noSuchMethod(
    Invocation.method(#applyPostDeleted, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyPostUpdated(_i13.PostUpdated? event) => super.noSuchMethod(
    Invocation.method(#applyPostUpdated, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void applyStateEvent(_i13.StateEvent? event) => super.noSuchMethod(
    Invocation.method(#applyStateEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emitUIEvent(_i13.UIEvent? event) => super.noSuchMethod(
    Invocation.method(#emitUIEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void addBatchPosts(
    List<_i14.PostModel>? posts, {
    _i15.FeedContext? context,
  }) => super.noSuchMethod(
    Invocation.method(#addBatchPosts, [posts], {#context: context}),
    returnValueForMissingStub: null,
  );

  @override
  void incrementCommentsCount(String? postId) => super.noSuchMethod(
    Invocation.method(#incrementCommentsCount, [postId]),
    returnValueForMissingStub: null,
  );

  @override
  void incrementFeedVersionHome() => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionHome, []),
    returnValueForMissingStub: null,
  );

  @override
  void incrementFeedVersionGlobal() => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionGlobal, []),
    returnValueForMissingStub: null,
  );

  @override
  int getNetworkFeedVersion(String? networkId) =>
      (super.noSuchMethod(
            Invocation.method(#getNetworkFeedVersion, [networkId]),
            returnValue: 0,
          )
          as int);

  @override
  void incrementFeedVersionNetwork(String? networkId) => super.noSuchMethod(
    Invocation.method(#incrementFeedVersionNetwork, [networkId]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i14.PostModel> resolvePosts(List<String>? ids, int? version) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePosts, [ids, version]),
            returnValue: <_i14.PostModel>[],
          )
          as List<_i14.PostModel>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i17.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PusherChannelsFlutter get pusher =>
      (super.noSuchMethod(
            Invocation.getter(#pusher),
            returnValue: _FakePusherChannelsFlutter_1(
              this,
              Invocation.getter(#pusher),
            ),
          )
          as _i3.PusherChannelsFlutter);

  @override
  _i4.ValueNotifier<_i17.SocketConnectionPhase> get connectionPhase =>
      (super.noSuchMethod(
            Invocation.getter(#connectionPhase),
            returnValue: _FakeValueNotifier_2<_i17.SocketConnectionPhase>(
              this,
              Invocation.getter(#connectionPhase),
            ),
          )
          as _i4.ValueNotifier<_i17.SocketConnectionPhase>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i6.Future<void> connect(String? jwtToken, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [jwtToken, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void on(String? event, void Function(dynamic)? handler) => super.noSuchMethod(
    Invocation.method(#on, [event, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void off(String? event, [void Function(dynamic)? handler]) =>
      super.noSuchMethod(
        Invocation.method(#off, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnectInternal({required bool? clearPhase}) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectInternal, [], {
              #clearPhase: clearPhase,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearAllListeners() => super.noSuchMethod(
    Invocation.method(#clearAllListeners, []),
    returnValueForMissingStub: null,
  );
}
